#!/usr/bin/env bash
set -eo pipefail

DIR=$1
[ -n "$DIR" ] || { >&2 echo "ERROR: Missing required argument"; exit 2; }
[[ "$DIR" =~ ^[a-zA-Z0-9/_-]+$ ]] || { >&2 echo "ERROR: Invalid input"; exit 2; }

docker run \
  --rm \
  -v "$PWD":"/mnt" \
  -w /mnt \
  lahmanja/archlinux:latest \
  bash -c "pacman -Sy && chown builder -R ${DIR} && su builder -c 'cd ${DIR} && yes | makepkg -Csi' && chown root -R ${DIR}"

