name: Deploy to AUR

on:
  push:
    branches:
      - master

jobs:
  push-to-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-permissions: true
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #- name: Add known hosts
      #  run: |
      #    mkdir -p ~/.ssh
      #    ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Push to remote repository
        run: |
          for dir in **/; do
            PACKAGE="${dir///}"
            git subtree push --prefix=$PACKAGE ssh://aur@aur.archlinux.org/$PACKAGE.git master
          done
