name: Nightly Updates

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    environment:
      name: nightly
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: |
          UPDATES=$(
            docker run --rm -v "$PWD:/mnt" -w "/mnt" lahmanja/nvchecker:2026-03-01 \
              bash -c "chown packager -R . && su packager -c 'python ./pkgreleaser.py' && chown $(id -u) -R ."
          )
          echo "$UPDATES" | jq -c '.[]' | while IFS= read -r UPDATE; do
            NAME=$(echo "$UPDATE" | jq -r '.name')
            OLD=$(echo "$UPDATE" | jq -r '.old_version')
            NEW=$(echo "$UPDATE" | jq -r '.new_version')
            MESSAGE="Bump ${NAME} from ${OLD} to ${NEW}"
            BRANCH="pkgreleaser/${NAME}/${NEW}"
            if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
              continue
            fi
            git checkout -b "$BRANCH" origin/master
            git add "$NAME/"
            git commit -m "$MESSAGE"
            git push -f -u origin "$BRANCH"
            gh pr create --base master --head "$BRANCH" --fill
            gh pr merge --auto --squash "$BRANCH"
            git checkout master
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
