name: Tests

on:
  push:
    branches:
      - "master"
      - "pkgreleaser/*"
  pull_request:

permissions: {}

jobs:
  presubmit:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'master' }}
    container: archlinux:base-devel
    steps:
      - run: pacman -Syu --noconfirm --needed git
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ./.github/actions/prek
        with:
          base: origin/master

  postsubmit:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    container: archlinux:base-devel
    steps:
      - run: pacman -Syu --noconfirm --needed git
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ./.github/actions/prek
        with:
          base: origin/master~1
